version: '2'
services:
  ipfs-daemon:
    image: 'ipfs/go-ipfs:latest'
    container_name: ipfs-daemon
    ports:
      - "4001:4001"
      - "5001:5001"
    user: "ipfs"
    command: [ "daemon", "--enable-pubsub-experiment" ]
